wallpaper = Image("nebulach-main-wallpaper.png");
logo = Image("nebulach-menu-icon.png");

screen_width = Window.GetWidth();
screen_height = Window.GetHeight();

wallpaper_sprite = Sprite(wallpaper);
wallpaper_sprite.SetX(0);
wallpaper_sprite.SetY(0);
wallpaper_sprite.SetZ(-10);

logo_sprite = Sprite(logo);
logo_sprite.SetX((screen_width - logo.GetWidth()) / 2);
logo_sprite.SetY((screen_height - logo.GetHeight()) / 2);
logo_sprite.SetZ(10);
